# ---------- Build Stage ----------
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app

# Clone your GitHub repo
RUN git clone --depth=1 https://github.com/Tejahaha/CulinaryCanvas.git .

# Go to backend folder
WORKDIR /app/FreshFork-Backend

# Build Spring Boot JAR
RUN mvn -q -DskipTests package

# ---------- Runtime Stage ----------
FROM eclipse-temurin:17-jre

WORKDIR /app

# Copy compiled JAR
COPY --from=build /app/FreshFork-Backend/target/*.jar app.jar

EXPOSE 8083

ENTRYPOINT ["java", "-jar", "app.jar"]
